<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Dictionary" Id="{2496496f-6f27-4201-9f0e-92026c6200d3}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK Dictionary
VAR
	initialSize : ULINT;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[
	]]></ST>
    </Implementation>
    <Folder Name="Constructor" Id="{b8245ce8-18aa-49cc-8afd-2dba8e1e6391}" />
    <Folder Name="Private" Id="{38d16013-6769-44a9-9cad-96b46152eab9}" />
    <Method Name="AddKeyValue" Id="{d65f77f4-4ccd-40df-9fd0-75019b8c0eda}">
      <Declaration><![CDATA[METHOD PUBLIC AddKeyValue
VAR_INPUT
	Key : T_MAXSTRING;
	Value : ANY;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Clear" Id="{7785c898-3c48-4fe2-81e1-cacbbc4b08af}">
      <Declaration><![CDATA[METHOD PUBLIC Clear
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="ContainsKey" Id="{c30a7e26-67f2-4551-b9c7-e531d1461757}">
      <Declaration><![CDATA[METHOD PUBLIC ContainsKey : BOOL;
VAR_INPUT
	Key : T_MAXSTRING;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Count" Id="{9ebe98eb-1d50-4553-a45d-3da249d13a8f}">
      <Declaration><![CDATA[PROPERTY PUBLIC Count : UINT]]></Declaration>
      <Get Name="Get" Id="{1c0d3937-4ab9-4f4e-aaa8-c17c25b4cf78}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="FB_init" Id="{7e7d6f02-34c0-4b55-896f-8686e4e10a42}" FolderPath="Constructor\">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	InitialSize : ULINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.initialSize := InitialSize;
InitalizeInternalArray(InitialSize);]]></ST>
      </Implementation>
    </Method>
    <Method Name="InitalizeInternalArray" Id="{1e3c0fa7-bf6a-46dd-be17-1f1dc42b637d}" FolderPath="Private\">
      <Declaration><![CDATA[METHOD PRIVATE InitalizeInternalArray
VAR_INPUT
	InitialSize : ULINT;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Remove" Id="{a24dcb40-efa1-4f1e-a731-a3646f2b28cd}">
      <Declaration><![CDATA[METHOD PUBLIC Remove
VAR_INPUT
	Key : T_MAXSTRING;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="TryGetValue" Id="{e9df9db0-5f25-404e-929c-5a02ea131685}">
      <Declaration><![CDATA[METHOD PUBLIC TryGetValue : BOOL;
VAR_INPUT
	Key : T_MAXSTRING;
	Destination : ANY;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>