<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="EnumeratorConnectionPool" Id="{686b84ea-8071-42e4-a9ec-0bbc3616c264}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK EnumeratorConnectionPool IMPLEMENTS I_EnumeratorConnectionUpdater
VAR
	head : I_EnumeratorConnectionItem;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="AddConnection" Id="{5f9be054-9bf9-4502-a4ac-a334213c9b07}">
      <Declaration><![CDATA[METHOD PUBLIC AddConnection
VAR_INPUT
	EnumeratorConnection : I_EnumeratorConnection;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="InvalidateEnumerators" Id="{f6041b2f-855a-4f31-8685-b1e2cceed099}">
      <Declaration><![CDATA[METHOD PUBLIC InvalidateEnumerators : I_Enumerator
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="RemoveConnection" Id="{d9b7d47b-a1bf-404e-9d4f-0502974893d5}">
      <Declaration><![CDATA[METHOD PUBLIC RemoveConnection
VAR_INPUT
	EnumeratorConnection : I_EnumeratorConnection;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>