<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MockEvent" Id="{2f9c554a-2034-412e-9e68-a68075e23a21}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK MockEvent IMPLEMENTS I_Event
VAR
	_name : T_MAXSTRING;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Constructor" Id="{92faa27c-d0c8-4754-92f3-0ceeacba4f84}" />
    <Method Name="FB_init" Id="{db307f70-0de2-41b4-a82b-6e906a827d0e}" FolderPath="Constructor\">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	Name : T_MAXSTRING;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[_name := Name;]]></ST>
      </Implementation>
    </Method>
    <Property Name="Name" Id="{bece4540-f580-49da-93aa-5dfe7c2b852d}">
      <Declaration><![CDATA[PROPERTY Name : T_MaxString]]></Declaration>
      <Get Name="Get" Id="{72762b61-636c-4abe-8de9-0196d164a96e}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[Name := _name;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>