<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="OnStackEventHandler" Id="{04ec90dd-37b5-44bb-b004-a8c6f5216d56}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT OnStackEventHandler EXTENDS MockEventHandler
VAR
	expectedOriginator : I_Stack;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Constructor" Id="{0cf30439-be12-4759-bd25-8a1e02ba4bc0}" />
    <Method Name="FB_init" Id="{1a2d643e-8d27-4603-9032-08df6f2604a9}" FolderPath="Constructor\">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	ExpectedOriginator : I_Stack;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[SetExpectedOriginator(ExpectedOriginator);]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetExpectedOriginator" Id="{356b25db-dfc3-4cae-bf21-ee001539e48d}">
      <Declaration><![CDATA[METHOD PUBLIC SetExpectedOriginator
VAR_INPUT
	ExpectedOriginator : I_Stack;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[THIS^.expectedOriginator := ExpectedOriginator;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>