<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Queue" Id="{1560f4e8-0d30-4cd0-8a35-4cb789c690a0}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'}
{attribute 'no_explicit_call' := 'do not call this POU directly'}
FUNCTION_BLOCK Queue
VAR
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Clear" Id="{ceb7ff56-02be-4942-a18b-24e6bdf422bf}">
      <Declaration><![CDATA[METHOD PUBLIC Clear
VAR_INPUT
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Count" Id="{74a80c93-5128-4663-bce6-db585e882711}">
      <Declaration><![CDATA[PROPERTY PUBLIC Count : UINT]]></Declaration>
      <Get Name="Get" Id="{cd074aca-ebef-41bc-a94d-415607b152ce}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="Dequeue" Id="{1ebc705c-ca50-401d-8bfc-812a17ac732a}">
      <Declaration><![CDATA[METHOD PUBLIC Dequeue : BOOL;
VAR_INPUT
	Destination : ANY;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Enqueue" Id="{5f56d2fb-90cb-4948-8ebe-7045801f934b}">
      <Declaration><![CDATA[METHOD PUBLIC Enqueue
VAR_INPUT
	Item : ANY;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Peek" Id="{dd37eb75-7dd6-45c5-8f42-587c3a759577}">
      <Declaration><![CDATA[METHOD PUBLIC Peek : BOOL;
VAR_INPUT
	Destination : ANY;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>