<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="DictionaryItem" Id="{3d8e8dd5-3e2c-4a9a-8943-9d753175c6b4}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'}
{attribute 'no_explicit_call' := 'do not call this POU directly'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK DictionaryItem EXTENDS LinkedListItem IMPLEMENTS I_DictionaryItem
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>