<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="QueueItem" Id="{698fcf05-9d43-4937-b564-68001b14eca1}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK QueueItem EXTENDS LinkedListItem IMPLEMENTS I_QueueItem
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>