<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="OnQueueEventHandler" Id="{dec9f6c6-29fb-4301-8bc0-a795a477dc72}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT OnQueueEventHandler EXTENDS MockEventHandler
VAR
	expectedOriginator : I_Queue;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Constructor" Id="{b3acf1eb-2d50-4884-a298-657cc346076d}" />
    <Method Name="FB_init" Id="{6421b87e-2b39-4f5b-baa3-4075dd24a1d3}" FolderPath="Constructor\">
      <Declaration><![CDATA[METHOD FB_init : BOOL
VAR_INPUT
	bInitRetains : BOOL; // if TRUE, the retain variables are initialized (warm start / cold start)
	bInCopyCode : BOOL;  // if TRUE, the instance afterwards gets moved into the copy code (online change)
	ExpectedOriginator : I_Queue;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[SetExpectedOriginator(ExpectedOriginator);]]></ST>
      </Implementation>
    </Method>
    <Method Name="SetExpectedOriginator" Id="{0646e90a-b0f9-4793-bdc8-ec3f1fb59bae}">
      <Declaration><![CDATA[METHOD PUBLIC SetExpectedOriginator
VAR_INPUT
	ExpectedOriginator : I_Queue;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[this^.expectedOriginator := ExpectedOriginator;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>