<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="Dictionary" Id="{2496496f-6f27-4201-9f0e-92026c6200d3}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'}
{attribute 'no_explicit_call' := 'do not call this POU directly'}
FUNCTION_BLOCK Dictionary
VAR
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Folder Name="Private" Id="{d1bfc11a-bfb8-4279-8f99-8ed64ee1dde6}" />
    <Method Name="AddKeyValue" Id="{d65f77f4-4ccd-40df-9fd0-75019b8c0eda}">
      <Declaration><![CDATA[METHOD PUBLIC AddKeyValue
VAR_INPUT
	Key : T_MAXSTRING;
	Value : ANY;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Clear" Id="{7785c898-3c48-4fe2-81e1-cacbbc4b08af}">
      <Declaration><![CDATA[METHOD PUBLIC Clear
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="ContainsKey" Id="{c30a7e26-67f2-4551-b9c7-e531d1461757}">
      <Declaration><![CDATA[METHOD PUBLIC ContainsKey : BOOL;
VAR_INPUT
	Key : T_MAXSTRING;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Property Name="Count" Id="{9ebe98eb-1d50-4553-a45d-3da249d13a8f}">
      <Declaration><![CDATA[PROPERTY PUBLIC Count : UINT]]></Declaration>
      <Get Name="Get" Id="{1c0d3937-4ab9-4f4e-aaa8-c17c25b4cf78}">
        <Declaration><![CDATA[VAR
	currentCount : UINT;
	currentItem : I_DictionaryItem;
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Method Name="GetItemByKey" Id="{af2545c1-cc5f-4ca6-921c-5788cb2a81eb}" FolderPath="Private\">
      <Declaration><![CDATA[METHOD PRIVATE GetItemByKey : I_DictionaryItem
VAR_INPUT
	Key : T_MAXSTRING;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Remove" Id="{a24dcb40-efa1-4f1e-a731-a3646f2b28cd}">
      <Declaration><![CDATA[METHOD PUBLIC Remove
VAR_INPUT
	Key : T_MAXSTRING;
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="TryGetValue" Id="{e9df9db0-5f25-404e-929c-5a02ea131685}">
      <Declaration><![CDATA[METHOD PUBLIC TryGetValue : BOOL;
VAR_INPUT
	Key : T_MAXSTRING;
	Destination : ANY;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>